on:
  push:
    branches:
      - develop
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          local-dir: ./build/
          server: ftp.webthesite.com
          server-dir: ${{ secrets.ftp_server_dir }}/_develop/
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
